package edu.spring.hibernate.bean;// default package
// Generated May 11, 2016 11:55:44 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CourseId generated by hbm2java
 */
@Embeddable
public class CourseId implements java.io.Serializable {

	private int courseid;
	private String code;
	private String title;
	private String hours;
	private String abbrev;

	public CourseId() {
	}

	public CourseId(int courseid) {
		this.courseid = courseid;
	}

	public CourseId(int courseid, String code, String title, String hours, String abbrev) {
		this.courseid = courseid;
		this.code = code;
		this.title = title;
		this.hours = hours;
		this.abbrev = abbrev;
	}

	@Column(name = "courseid", nullable = false)
	public int getCourseid() {
		return this.courseid;
	}

	public void setCourseid(int courseid) {
		this.courseid = courseid;
	}

	@Column(name = "code", length = 15)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "title", length = 100)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "hours", length = 10)
	public String getHours() {
		return this.hours;
	}

	public void setHours(String hours) {
		this.hours = hours;
	}

	@Column(name = "abbrev", length = 15)
	public String getAbbrev() {
		return this.abbrev;
	}

	public void setAbbrev(String abbrev) {
		this.abbrev = abbrev;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CourseId))
			return false;
		CourseId castOther = (CourseId) other;

		return (this.getCourseid() == castOther.getCourseid())
				&& ((this.getCode() == castOther.getCode()) || (this.getCode() != null && castOther.getCode() != null
						&& this.getCode().equals(castOther.getCode())))
				&& ((this.getTitle() == castOther.getTitle()) || (this.getTitle() != null
						&& castOther.getTitle() != null && this.getTitle().equals(castOther.getTitle())))
				&& ((this.getHours() == castOther.getHours()) || (this.getHours() != null
						&& castOther.getHours() != null && this.getHours().equals(castOther.getHours())))
				&& ((this.getAbbrev() == castOther.getAbbrev()) || (this.getAbbrev() != null
						&& castOther.getAbbrev() != null && this.getAbbrev().equals(castOther.getAbbrev())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCourseid();
		result = 37 * result + (getCode() == null ? 0 : this.getCode().hashCode());
		result = 37 * result + (getTitle() == null ? 0 : this.getTitle().hashCode());
		result = 37 * result + (getHours() == null ? 0 : this.getHours().hashCode());
		result = 37 * result + (getAbbrev() == null ? 0 : this.getAbbrev().hashCode());
		return result;
	}

}
