package edu.spring.hibernate.bean;// default package
// Generated Apr 18, 2016 7:45:25 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;

import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.AssociationOverride;
import javax.persistence.AssociationOverrides;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * Schedule generated by hbm2java
 */
@Entity
@AssociationOverrides({
	@AssociationOverride(name="fk.slots",joinColumns=@JoinColumn(name="slotid")),
	@AssociationOverride(name="fk.offeredcourse",joinColumns=@JoinColumn(name="offid"))
})
@Table(name = "schedule", catalog = "sch2k16")
public class Schedule implements java.io.Serializable {
	@EmbeddedId
	ScheduleFk fk =  new ScheduleFk();
	
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "schid")
	private Integer schid;
	@Column(name = "occupied")
	private Integer occupied;

	public Schedule() {
	}
	
	public Schedule(Offeredcourse offeredcourse,Slots slot,Integer occ) {
		setSlot(slot);
		setOccupied(occ);
		setOfferedcourse(offeredcourse);
	}
	

	
	

	
	
	
	public Integer getOccupied() {
		return this.occupied;
	}

	public void setOccupied(Integer occupied) {
		this.occupied = occupied;
	}





	public ScheduleFk getFk() {
		return fk;
	}





	public void setFk(ScheduleFk fk) {
		this.fk = fk;
	}
	
	
	@Transient
	public Offeredcourse getOfferdcourse(){
		return getFk().getOfferedcourse();
	}
	
	public void setOfferedcourse(Offeredcourse offeredcourse) {
		getFk().setOfferedcourse(offeredcourse);
	}
	
	@Transient
	public Slots getSlot() {
		return getFk().getSlot();
	}
	
	public void setSlot(Slots slot) {
		getFk().setSlot(slot);
	}

	public Integer getSchid() {
		return schid;
	}

	public void setSchid(Integer schid) {
		this.schid = schid;
	}
}
