package edu.spring.hibernate.bean;

// default package
// Generated May 11, 2016 7:42:13 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Sectiondetails generated by hbm2java
 */
@Entity
@Table(name = "sectiondetails", catalog = "sch2k16")
public class Sectiondetails implements java.io.Serializable {

	private Integer sdid;
	private Integer offid;
	private Integer secid;

	public Sectiondetails() {
	}

	public Sectiondetails(Integer offid, Integer secid) {
		this.offid = offid;
		this.secid = secid;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "sdid", unique = true, nullable = false)
	public Integer getSdid() {
		return this.sdid;
	}

	public void setSdid(Integer sdid) {
		this.sdid = sdid;
	}

	@Column(name = "offid")
	public Integer getOffid() {
		return this.offid;
	}

	public void setOffid(Integer offid) {
		this.offid = offid;
	}

	@Column(name = "secid")
	public Integer getSecid() {
		return this.secid;
	}

	public void setSecid(Integer secid) {
		this.secid = secid;
	}

}
