package awt.project.schedule.bean;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.CascadeType;

// default package
// Generated May 11, 2016 7:42:13 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CourseId generated by hbm2java
 */
@Entity
@Table(name = "course", catalog = "sch2k16")
public class Course implements java.io.Serializable {
	@Id
	@Column(name = "courseid", nullable = false)
	private int courseid;
	@Column(name = "code", length = 15)
	private String code;
	@Column(name = "title", length = 100)
	private String title;
	@Column(name = "hours", length = 10)
	private String hours;
	@Column(name = "abbrev", length = 15)
	private String abbrev;
	@OneToMany(cascade=CascadeType.ALL)
	@JoinColumn(name="courseid")
	List<Offeredcourse> offCourse = new ArrayList<Offeredcourse>();


	public int getCourseid() {
		return this.courseid;
	}

	public void setCourseid(int courseid) {
		this.courseid = courseid;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	
	public String getHours() {
		return this.hours;
	}

	public void setHours(String hours) {
		this.hours = hours;
	}

	public String getAbbrev() {
		return this.abbrev;
	}

	public void setAbbrev(String abbrev) {
		this.abbrev = abbrev;
	}

	public List<Offeredcourse> getOffCourse() {
		return offCourse;
	}

	public void setOffCourse(List<Offeredcourse> offCourse) {
		this.offCourse = offCourse;
	}





}
