package awt.project.schedule.bean;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.CascadeType;

// default package
// Generated May 11, 2016 7:42:13 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Offeredcourse generated by hbm2java
 */
@Entity
@Table(name = "offeredcourse", catalog = "sch2k16")
public class Offeredcourse implements java.io.Serializable {
	@Id
	@Column(name = "offid", unique = true, nullable = false)
	private int offid;
	@ManyToOne
	@JoinColumn(name="courseid")
	Course course;
	@ManyToOne
	@JoinColumn(name="teacherid")
	Teacher teacher;
	@OneToMany(cascade=CascadeType.ALL, mappedBy="fk.offeredcourse")
	private List<Schedule> schedule = new ArrayList<Schedule>();
	
	public Offeredcourse() {
	}

	public Offeredcourse(int offid) {
		this.offid = offid;
	}

	public Offeredcourse(int offid, Integer courseid, Integer teacherid) {
		this.offid = offid;
	
	}

	public int getOffid() {
		return this.offid;
	}

	public void setOffid(int offid) {
		this.offid = offid;
	}




	public List<Schedule> getSchedule() {
		return schedule;
	}

	public void setSchedule(List<Schedule> schedule) {
		this.schedule = schedule;
	}

	public Course getCourse() {
		return course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	public Teacher getTeacher() {
		return teacher;
	}

	public void setTeacher(Teacher teacher) {
		this.teacher = teacher;
	}

}
