package awt.project.schedule.bean;

import javax.persistence.CascadeType;

// default package
// Generated May 11, 2016 7:42:13 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Slots generated by hbm2java
 */
@Entity
@Table(name = "slots", catalog = "sch2k16")
public class Slots implements java.io.Serializable {
	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "slotid", unique = true, nullable = false)
	private Integer slotid;
	@Column(name = "dayid", nullable = false)
	private int dayid;
	@Column(name = "slottypeid", nullable = false)
	private int slottypeid;
	@Column(name = "roomid", nullable = false)
	private int roomid;
	
	@OneToMany(cascade=CascadeType.ALL, mappedBy="fk.slots")
	private List<Schedule> schedule = new ArrayList<Schedule>();
	
	public Slots() {
	}

	public Slots(int dayid, int slottypeid, int roomid) {
		this.dayid = dayid;
		this.slottypeid = slottypeid;
		this.roomid = roomid;
	}


	public Integer getSlotid() {
		return this.slotid;
	}

	public void setSlotid(Integer slotid) {
		this.slotid = slotid;
	}

	public int getDayid() {
		return this.dayid;
	}

	public void setDayid(int dayid) {
		this.dayid = dayid;
	}

	public int getSlottypeid() {
		return this.slottypeid;
	}

	public void setSlottypeid(int slottypeid) {
		this.slottypeid = slottypeid;
	}

	
	public int getRoomid() {
		return this.roomid;
	}

	public void setRoomid(int roomid) {
		this.roomid = roomid;
	}

	public List<Schedule> getSchedule() {
		return schedule;
	}

	public void setSchedule(List<Schedule> schedule) {
		this.schedule = schedule;
	}

}
