package awt.project.schedule.bean;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.CascadeType;

// default package
// Generated May 11, 2016 7:42:13 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Teacher generated by hbm2java
 */
@Entity
@Table(name = "teacher", catalog = "sch2k16")
public class Teacher implements java.io.Serializable {

	@Id
	@Column(name = "teacherid", unique = true, nullable = false)
	private int teacherid;
	@Column(name = "teachername", length = 50)
	private String teachername;
	@OneToMany(cascade=CascadeType.ALL)
	@JoinColumn(name="teacherid")
	List<Offeredcourse> offCourse = new ArrayList<Offeredcourse>();
	public Teacher() {
	}

	public Teacher(int teacherid) {
		this.teacherid = teacherid;
	}

	public Teacher(int teacherid, String teachername) {
		this.teacherid = teacherid;
		this.teachername = teachername;
	}
	public int getTeacherid() {
		return this.teacherid;
	}

	public void setTeacherid(int teacherid) {
		this.teacherid = teacherid;
	}

	public String getTeachername() {
		return this.teachername;
	}

	public void setTeachername(String teachername) {
		this.teachername = teachername;
	}

}
