package edu.springhiber.project.bean;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Teacher generated by hbm2java
 */
@Entity
@Table(name = "teacher", catalog = "sch2k16")
public class Teacher implements java.io.Serializable {

	private int teacherid;
	private String teachername;

	public Teacher() {
	}

	public Teacher(int teacherid) {
		this.teacherid = teacherid;
	}

	public Teacher(int teacherid, String teachername) {
		this.teacherid = teacherid;
		this.teachername = teachername;
	}

	@Id

	@Column(name = "teacherid", unique = true, nullable = false)
	public int getTeacherid() {
		return this.teacherid;
	}

	public void setTeacherid(int teacherid) {
		this.teacherid = teacherid;
	}

	@Column(name = "teachername", length = 50)
	public String getTeachername() {
		return this.teachername;
	}

	public void setTeachername(String teachername) {
		this.teachername = teachername;
	}

}
