package edu.springhiber.project.bean;

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VslottypeId generated by hbm2java
 */
@Embeddable
public class VslottypeId implements java.io.Serializable {

	private int slottypeid;
	private String duration;
	private Integer slotno;
	private BigDecimal sort;
	private int subslotid;
	private Long occupied;

	public VslottypeId() {
	}

	public VslottypeId(int slottypeid, BigDecimal sort, int subslotid) {
		this.slottypeid = slottypeid;
		this.sort = sort;
		this.subslotid = subslotid;
	}

	public VslottypeId(int slottypeid, String duration, Integer slotno, BigDecimal sort, int subslotid, Long occupied) {
		this.slottypeid = slottypeid;
		this.duration = duration;
		this.slotno = slotno;
		this.sort = sort;
		this.subslotid = subslotid;
		this.occupied = occupied;
	}

	@Column(name = "slottypeid", nullable = false)
	public int getSlottypeid() {
		return this.slottypeid;
	}

	public void setSlottypeid(int slottypeid) {
		this.slottypeid = slottypeid;
	}

	@Column(name = "duration", length = 50)
	public String getDuration() {
		return this.duration;
	}

	public void setDuration(String duration) {
		this.duration = duration;
	}

	@Column(name = "slotno")
	public Integer getSlotno() {
		return this.slotno;
	}

	public void setSlotno(Integer slotno) {
		this.slotno = slotno;
	}

	@Column(name = "sort", nullable = false, precision = 12, scale = 1)
	public BigDecimal getSort() {
		return this.sort;
	}

	public void setSort(BigDecimal sort) {
		this.sort = sort;
	}

	@Column(name = "subslotid", nullable = false)
	public int getSubslotid() {
		return this.subslotid;
	}

	public void setSubslotid(int subslotid) {
		this.subslotid = subslotid;
	}

	@Column(name = "occupied")
	public Long getOccupied() {
		return this.occupied;
	}

	public void setOccupied(Long occupied) {
		this.occupied = occupied;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VslottypeId))
			return false;
		VslottypeId castOther = (VslottypeId) other;

		return (this.getSlottypeid() == castOther.getSlottypeid())
				&& ((this.getDuration() == castOther.getDuration()) || (this.getDuration() != null
						&& castOther.getDuration() != null && this.getDuration().equals(castOther.getDuration())))
				&& ((this.getSlotno() == castOther.getSlotno()) || (this.getSlotno() != null
						&& castOther.getSlotno() != null && this.getSlotno().equals(castOther.getSlotno())))
				&& ((this.getSort() == castOther.getSort()) || (this.getSort() != null && castOther.getSort() != null
						&& this.getSort().equals(castOther.getSort())))
				&& (this.getSubslotid() == castOther.getSubslotid())
				&& ((this.getOccupied() == castOther.getOccupied()) || (this.getOccupied() != null
						&& castOther.getOccupied() != null && this.getOccupied().equals(castOther.getOccupied())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getSlottypeid();
		result = 37 * result + (getDuration() == null ? 0 : this.getDuration().hashCode());
		result = 37 * result + (getSlotno() == null ? 0 : this.getSlotno().hashCode());
		result = 37 * result + (getSort() == null ? 0 : this.getSort().hashCode());
		result = 37 * result + this.getSubslotid();
		result = 37 * result + (getOccupied() == null ? 0 : this.getOccupied().hashCode());
		return result;
	}

}
