package edu.springmvc.hiber.bean;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Offeredcourse generated by hbm2java
 */
@Entity
@Table(name = "offeredcourse", catalog = "sch2k16")
public class Offeredcourse implements java.io.Serializable {

	private int offid;
	private Integer courseid;
	private Integer teacherid;

	public Offeredcourse() {
	}

	public Offeredcourse(int offid) {
		this.offid = offid;
	}

	public Offeredcourse(int offid, Integer courseid, Integer teacherid) {
		this.offid = offid;
		this.courseid = courseid;
		this.teacherid = teacherid;
	}

	@Id

	@Column(name = "offid", unique = true, nullable = false)
	public int getOffid() {
		return this.offid;
	}

	public void setOffid(int offid) {
		this.offid = offid;
	}

	@Column(name = "courseid")
	public Integer getCourseid() {
		return this.courseid;
	}

	public void setCourseid(Integer courseid) {
		this.courseid = courseid;
	}

	@Column(name = "teacherid")
	public Integer getTeacherid() {
		return this.teacherid;
	}

	public void setTeacherid(Integer teacherid) {
		this.teacherid = teacherid;
	}

}
