package edu.springmvc.hiber.bean;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Room generated by hbm2java
 */
@Entity
@Table(name = "room", catalog = "sch2k16")
public class Room implements java.io.Serializable {

	private int roomid;
	private String roomno;
	private String campus;
	private String roomtype;

	public Room() {
	}

	public Room(int roomid) {
		this.roomid = roomid;
	}

	public Room(int roomid, String roomno, String campus, String roomtype) {
		this.roomid = roomid;
		this.roomno = roomno;
		this.campus = campus;
		this.roomtype = roomtype;
	}

	@Id

	@Column(name = "roomid", unique = true, nullable = false)
	public int getRoomid() {
		return this.roomid;
	}

	public void setRoomid(int roomid) {
		this.roomid = roomid;
	}

	@Column(name = "roomno", length = 20)
	public String getRoomno() {
		return this.roomno;
	}

	public void setRoomno(String roomno) {
		this.roomno = roomno;
	}

	@Column(name = "campus", length = 20)
	public String getCampus() {
		return this.campus;
	}

	public void setCampus(String campus) {
		this.campus = campus;
	}

	@Column(name = "roomtype", length = 25)
	public String getRoomtype() {
		return this.roomtype;
	}

	public void setRoomtype(String roomtype) {
		this.roomtype = roomtype;
	}

}
