package edu.springmvc.hiber.bean;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Slots generated by hbm2java
 */
@Entity
@Table(name = "slots", catalog = "sch2k16")
public class Slots implements java.io.Serializable {

	private Integer slotid;
	private int dayid;
	private int slottypeid;
	private int roomid;

	public Slots() {
	}

	public Slots(int dayid, int slottypeid, int roomid) {
		this.dayid = dayid;
		this.slottypeid = slottypeid;
		this.roomid = roomid;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "slotid", unique = true, nullable = false)
	public Integer getSlotid() {
		return this.slotid;
	}

	public void setSlotid(Integer slotid) {
		this.slotid = slotid;
	}

	@Column(name = "dayid", nullable = false)
	public int getDayid() {
		return this.dayid;
	}

	public void setDayid(int dayid) {
		this.dayid = dayid;
	}

	@Column(name = "slottypeid", nullable = false)
	public int getSlottypeid() {
		return this.slottypeid;
	}

	public void setSlottypeid(int slottypeid) {
		this.slottypeid = slottypeid;
	}

	@Column(name = "roomid", nullable = false)
	public int getRoomid() {
		return this.roomid;
	}

	public void setRoomid(int roomid) {
		this.roomid = roomid;
	}

}
